### ISSUE TITLE
Boson Exception on Interrupt Handling

### ISSUE THREAD

**Issue by ramsingla** [duckie/boson#3]
I am writing a server application and want to handle interrupt signal. I added the following to the main application.

```
void signal_handler(int x) {
  // cleanup code
}
signal(SIGINT, signal_handler);
```
it throws the following error.

```
terminate called after throwing an instance of 'boson::exception'
  what():  Syscall error (epoll_wait) EINTR : Interrupted system call
Aborted (core dumped)
```

I would be interested in knowing what is the best way to handle when using boson.

**Comment by duckie** [comment]
Hi ! 

Thank you for your feedback. The fact is : signal handling in multi-threaded applications is hard and `boson` should provide you an API to do it easily.

In the meantime, you can still handle the signals in `boson`. The first step is to disable signal handling properly. For this you shall not use `signal` since its behavior is undefined in multi-threaded environments. Be aware that even with one thread, a `boson` process is multi-threaded because the single thread is separated from the main one, which blocks waiting for the end of `boson::run`.

There is two ways to handle signals:
- Choose to run a dedicated thread for signal handling which will do just this. This works at the condition  you do not starve the thread of blocking calls.
- Handle the signals in all boson threads. When a signal occurs, only one shall be woken up.

I have an example in preparation, but it only works for method 1. Method 2 is broken for now and probably need bugfixes. Here it is:

```
#include <signal.h>
#include <sys/signalfd.h>
#include <iostream>
#include "boson/select.h"
#include "boson/boson.h"
#include "boson/channel.h"
#include "boson/syscalls.h"

using namespace boson;
using sigfdinfo_t = signalfd_siginfo;
static constexpr size_t nb_threads = 8;

void handle_signals(int signal_fd) {
  sigfdinfo_t info{};
  while(0 < boson::read(signal_fd, &info, sizeof(sigfdinfo_t))) {
    std::cout << "Received signal " << info.ssi_signo << std::endl;
  }
}

int main(int argc, char *argv[]) {
  // Block signals in all threads
  sigset_t mask;
  sigemptyset(&mask);
  sigaddset(&mask, SIGTERM);
  sigaddset(&mask, SIGINT);
  pthread_sigmask(SIG_BLOCK, &mask, nullptr);
  int signal_fd = signalfd(-1, &mask, 0);

  // Start a boson engine with signal handling
  boson::run(nb_threads, [signal_fd]() {
    start(handle_signals, signal_fd);
    // Do what you mean
  });
}
```

I'll keep you posted when I got news.

**Comment by duckie** [comment]
Hey @ramsingla, any chance you had a look at it ?

**Comment by duckie** [comment]
No news here so I close the topic.
