### ISSUE TITLE
Quick Tutorial tweak to use non-const fails to compile

### ISSUE THREAD

**Issue by omac777** [duckie/boson#4]
In your quick tutorial located:
https://github.com/duckie/boson/blob/master/docs/md/manual.md

rather than using:
channel<std::string, 2> msg_chan;

I wanted to use:
```
#include <unistd.h>
channel<std::string, sysconf(_SC_NPROCESSORS_ONLN)> msg_chan;
```

but it fails to compile.
"not usable in a constant expression"

To compile I am using the following:
`g++ basic_boson_channel.cc -o basic_boson_channel -std=c++14 -Wno-pragmas -I/home/dma2/mygocppchannels/boson/src/boson -I/home/dma2/mygocppchannels/boson/build/src/boson -I/home/dma2/mygocppchannels/boson/3rdparty/fmt -I/home/dma2/mygocppchannels/boson/3rdparty/wfqueue/SYSTEM -I/home/dma2/mygocppchannels/boson/3rdparty/wfqueue -rdynamic -L/home/dma2/mygocppchannels/boson/build/lib -lboson -lfmt -lwfqueue -lpthread -fpermissive
`
Thank you for listening.

**Comment by duckie** [comment]
Hi 

Unfortunately, the numbers of processors available on the machine running the binary cannot be known at compilation time since it depends on each host. 

If you absolutely need it, you can force a value by hand knowing you target a specific host. Something like 

```C++
uint const sc_nprocessors_onln = THE_NUMBER_YOU_TARGET;
//.. later on..
channel<std::string, sc_nprocessors_onln> msg_chan;
```

It should work. You can even make it a compilation option to change it at built time. 

It could be argued that a channel size should be dynamic. Well, I believe both are useful and I did not had the time to implement the dynamic one yet.
